# Generated by Django 3.1 on 2020-08-09 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='Icon',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_id',
        ),
        migrations.RemoveField(
            model_name='services',
            name='Service_id',
        ),
        migrations.AddField(
            model_name='service',
            name='Category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='Featured',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='Featured_Price',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='service',
            name='Sub_Category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='services',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Featured',
        ),
    ]
